### ISSUE TITLE
Samples for Orleans 2.0

### ISSUE THREAD

**Issue by KSemenenko** [OrleansContrib/Orleans.CosmosDB#14]
Hi, I try to use Cosmos DB in Orleans 2.0, but it doesn't work.
Maybe you can provide samples how to I can config it?

**Comment by galvesribeiro** [comment]
Hello @KSemenenko. What is the problem you are having with 2.0? I have it working so far and the same instructions are at the README page here: https://github.com/OrleansContrib/Orleans.CosmosDB/blob/master/README.md#configuration

Did you checked that?

**Comment by KSemenenko** [comment]
as for me it's looks like this:
```cs
 serviceCollection.AddCosmosDBGrainStorageAsDefault(options =>
            {
                options.AccountEndpoint = CosmosDbUri;
                options.AccountKey = CosmosDbKey;
                options.ConnectionMode = Microsoft.Azure.Documents.Client.ConnectionMode.Direct;
                options.DropDatabaseOnInit = true;
                options.AutoUpdateStoredProcedures = true;
                options.CanCreateResources = true;
                options.DB = "Orleans";
            });
```
and I don't use ClusterConfiguration.

**Comment by galvesribeiro** [comment]
Sorry, You are right. The README.md was outdated. Please check it now.

Thank you!

**Comment by KSemenenko** [comment]
Thank you so much! You have a wonderful project!
