### ISSUE TITLE
Exception with ConsistencyLevel 

### ISSUE THREAD

**Issue by KSemenenko** [OrleansContrib/Orleans.CosmosDB#15]
I get this error when starting Silos: 
ArgumentException: ConsistencyLevel Strong specified in the request is invalid when service is configured with consistency level Session. Ensure the request consistency level is not stronger than the service consistency level.

**Comment by galvesribeiro** [comment]
Hello @KSemenenko. That is CosmosDB saying that your default (service) consistency level at your CosmosDB account is weaker than your Database, Collection, or Request consistency levels. 

You can learn more here: https://docs.microsoft.com/en-us/azure/cosmos-db/consistency-levels
