### ISSUE TITLE
Expose JsonSerializerSettings for the user

### ISSUE THREAD

**Issue by Karamell** [OrleansContrib/Orleans.CosmosDB#17]
I need to use JsonSerializerSettings to set up the serializer for Nodatime Instant and Duration. My issue is probably related to #6. Is custom serializer settings not possible at all?

**Comment by galvesribeiro** [comment]
Hello @Karamell 

I intentionally didn't opened the settings to be changed as it would allow people to change the behavior of the storage provider which as you linked, was failing on #6 

If you want to submit a PR for that issue solution and at same time safely expose the settings, I would appreciate that.

**Comment by COCPORN** [comment]
I went added the option of configuring the JsonSerializationSettings in https://github.com/OrleansContrib/Orleans.CosmosDB/pull/21

**Comment by galvesribeiro** [comment]
Fixed on #21
