### ISSUE TITLE
Cannot resolve scoped service 'CosmosDBStorageOptions'

### ISSUE THREAD

**Issue by Geofencer** [OrleansContrib/Orleans.CosmosDB#40]
In a fresh .NETCore 3.1 project I'm trying to build an Orleans silo using the new generic host builder.
Unfortunately I keep running into the following error:

> _System.InvalidOperationException: 'Cannot resolve scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[Orleans.Persistence.CosmosDB.CosmosDBStorageOptions]' from root provider.'_

UseCosmosDBMembership and UseCosmosDBReminderService work perfectly. As soon as I add GrainStorage(AsDefault) the error occurs.

As the DI cannot resolve CosmosDBStorageOptions I suspect I'm missing a package or reference. 

Besides a few Serilog and Swashbuckle nuget-packages the following Orleans packages are installed:
- Microsoft.Orleans.Server v3.0.2
- Orleans.Clustering.CosmosDB v3.0.0
- Orleans.Persistence.CosmosDB v3.0.0
- Orleams.Reminders.CosmosDB v3.0.0

My HostBuilder looks as follows:

```c#
var Host = new HostBuilder()
    .UseContentRoot(Directory.GetCurrentDirectory())

    .UseDefaultServiceProvider((Context, Options) =>
    {
        var IsDevelopment = Context.HostingEnvironment.IsDevelopment();
        Options.ValidateScopes = IsDevelopment;
        Options.ValidateOnBuild = IsDevelopment;
    })
    .UseSerilog()
    .UseOrleans(SiloBuilder =>
    {
        _ = SiloBuilder.Configure<ClusterOptions>(ClusterOptions =>
        {
            ClusterOptions.ClusterId = "SomeId";
            ClusterOptions.ServiceId = "SomeId"; 
        });
        
        _ = SiloBuilder.ConfigureEndpoints(siloPort: x, gatewayPort: x);

        // Silo clustering persistance provider.
        _ = SiloBuilder.UseCosmosDBMembership(Options =>
        {
            // Configuration
        });

        // Default grain persistance storage provider.
        _ = SiloBuilder.AddCosmosDBGrainStorageAsDefault(Options =>
        {
            // Configuration
        });

        // Reminder persistance storage provider.
        _ = SiloBuilder.UseCosmosDBReminderService(Options =>
        {
            // Configuration
        });
    })
    .ConfigureWebHostDefaults(WebHostBuilder =>  
        _ = WebHostBuilder.UseStartup<HostStartup>()                        
        .UseUrls("SomeUrl"))
    .Build();
```

Any clue as to what I'm doing wrong? Or am I facing a compatibility bug with the newer Orleans versions?

Kind regards,
Jan van Linge

**Comment by SixFive7** [comment]
Hi, we are experiencing the same issue.

Orleans.Clustering.CosmosDB and Reminders.CosmosDB are both fine. Persistence.CosmosDB however is not.

**Comment by iskandersierra** [comment]
I'm also experiencing this issue.

I see in this line of the [storage factory](https://github.com/OrleansContrib/Orleans.CosmosDB/blob/master/src/Orleans.Persistence.CosmosDB/CosmosDBGrainStorage.cs#L465) is where the service provider is unable to find the instance of  `IOptionsSnapshot<CosmosDBStorageOptions>`.

In this other line on the [storage extensions](https://github.com/OrleansContrib/Orleans.CosmosDB/blob/master/src/Orleans.Persistence.CosmosDB/StorageExtensions.cs#L283) the `AddOptions` method is only called if the callback is set (isn't it?). It might be the bug.

I tried using the following methods:
- `AddCosmosDBGrainStorageAsDefault` with no parameters
- `AddCosmosDBGrainStorageAsDefault` with options parameter
- `AddCosmosDBGrainStorageAsDefault` with OptionsBuilder parameter
- The non-default variants with their variants
None of them worked, giving the same issue that @SixFive7 and @Geofencer are reporting.
Please @galvesribeiro or @Ulriksen if you could take a look at this issue it would be most appreciated.

**Comment by 13346437240** [comment]
I'm also experiencing the same issue.

And I use blow code to configuration host:
`host.UseDefaultServiceProvider(options => options.ValidateScopes = false);`
then my program worked.

But I'm not sure that will lead to any problem.

**Comment by ReubenBond** [comment]
Does manually calling `builder.ConfigureServices(services => services.AddOptions());` resolve this?

**Comment by Geofencer** [comment]
@13346437240  Great find, for us this would be a valid workaround since we'd enabled the scope validation check on debugging only.

@ReubenBond Thanks for taking the time to look at this. Your solution indeed resolves the issue :-) Can you give us a hint as to what this line of code does and how it resolves the issue?

![image](https://user-images.githubusercontent.com/59770651/75658480-b4ece680-5c68-11ea-9222-0d69874652e0.png)

**Comment by ReubenBond** [comment]
I'm honestly not sure why that is needed, since all host builders automatically call that method. Perhaps there's some versioning mismatch.

The method adds several generic services to the container, from the Microsoft.Extensions.Options package:

```C#
services.TryAdd(ServiceDescriptor.Singleton(typeof(IOptions<>), typeof(OptionsManager<>)));
services.TryAdd(ServiceDescriptor.Scoped(typeof(IOptionsSnapshot<>), typeof(OptionsManager<>)));
services.TryAdd(ServiceDescriptor.Singleton(typeof(IOptionsMonitor<>), typeof(OptionsMonitor<>)));
services.TryAdd(ServiceDescriptor.Transient(typeof(IOptionsFactory<>), typeof(OptionsFactory<>)));
services.TryAdd(ServiceDescriptor.Singleton(typeof(IOptionsMonitorCache<>), typeof(OptionsCache<>)));
```

**Comment by Geofencer** [comment]
This makes perfect sense with what I've seen so far. Thanks for the help!

**Comment by jbockle** [comment]
may be related to https://github.com/dotnet/orleans/issues/5543

**Comment by ReubenBond** [comment]
The correct workaround is something like this:

```C#
public void Register(IServiceCollection services)
{
    services.AddSingleton<IOptionsSnapshot<CosmosDBStorageOptions>, WorkaroundOptions<CosmosDBStorageOptions>>();
}

public class WorkaroundOptions<T> : IOptionsSnapshot<T>
{
    private readonly IOptionsMonitor<T> options;

    public WorkaroundOptions(IOptionsMonitor<T> options)
    {
        this.options = options;
    }

    public T Value => this.options.CurrentValue;
    public T Get(string name) => this.options.Get(name);
}
```

I see that I introduced an issue in #44 which was then rectified in #44
